# Generated by Django 4.2.7 on 2023-12-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_category_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
