# Generated by Django 4.2.7 on 2023-12-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_category_created_remove_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
