# Generated by Django 4.2.7 on 2023-12-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_alter_book_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='username',
        ),
    ]
