# Generated by Django 5.0 on 2023-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookapp/categoryimages/'),
        ),
    ]
