# Generated by Django 5.0 on 2023-12-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
